[tool.poetry]
name = "lab5"
version = "0.1.0"
description = ""
authors = ["a.emelyanov <alexndr.emelyanov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
beautifultable = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
